package com.ciq.sms.queries;

public interface StudentQueries {
	String SMS_INSERT_QUERY ="INSERT INTO STUDENT_TAB  (SID,SNAME,SFEE) VALUES(?,?,?)";
	String SMS_UPDATE_QUERY ="UPDATE  STUDENT_TAB  SET SNAME=?,SFEE=? WHERE SID=? ";
	String SMS_DELETE_QUERY ="DELETE FROM   STUDENT_TAB   WHERE SID=? ";
	String SMS_FIND_BY_ID_QUERY ="SELECT * FROM STUDENT_TAB WHERE SID=? ";
	String SMS_FIND_BY_NAME_QUERY ="SELECT * FROM STUDENT_TAB WHERE SNAME=? ";
	String SMS_FIND_BY_ALL_QUERY ="SELECT * FROM STUDENT_TAB";



	


}
